# Generated by Django 4.1.2 on 2022-10-28 15:23

from django.db import migrations, models
import django.db.models.deletion
import personel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=personel.models.personel_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.personel')),
            ],
        ),
    ]
