# Generated by Django 4.1.2 on 2022-10-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0005_alter_personelrow_personel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personelrow',
            old_name='end_date',
            new_name='school_end_date',
        ),
        migrations.RenameField(
            model_name='personelrow',
            old_name='start_date',
            new_name='school_start_date',
        ),
    ]
