# Generated by Django 4.1.2 on 2022-11-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0006_rename_end_date_personelrow_school_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='personel',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
