# Generated by Django 4.1.2 on 2023-01-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0007_alter_personel_image_alter_personel_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaleducation',
            name='school',
            field=models.CharField(max_length=100),
        ),
    ]
