# Generated by Django 4.1.2 on 2022-10-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='personel',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='personel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
