# Generated by Django 4.1.2 on 2022-10-28 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0002_alter_personel_address_alter_personel_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaleducation',
            name='personel',
        ),
        migrations.CreateModel(
            name='PersonelRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.personaleducation')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.personel')),
            ],
        ),
    ]
